services:
  genshin_banpick_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - genshin_banpick_db_vol:/var/lib/mysql
    networks:
      - genshin_banpick_net

networks:
  genshin_banpick_net:
    name: genshin_banpick_net
    driver: bridge

volumes:
  genshin_banpick_db_vol:
